cask_args appdir: '/Applications'

tap 'homebrew/core'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'heroku/brew'

brew 'awscli'
brew 'certbot'
brew 'git'
brew 'heroku'
brew 'ffmpeg'
brew 'nvm'
brew 'jenv'
brew 'mas' # Mac App Store
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'python@2'
brew 'rbenv'
brew 'ruby-build' # rbenv installs it, but also, let's be explicit
brew 'redis'
brew 'sass'
brew 'sqlite'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'
brew 'z'
brew 'zsh'
brew 'zsh-completions'

# Applications
cask '1password'
cask 'acorn'
cask 'backblaze'
cask 'backblaze-downloader'
cask 'bbedit'
cask 'choosy'
cask 'clockify'
cask 'docker'
cask 'encryptme'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
# cask 'highland' # Not actually supported; I wish
cask 'iterm2'
cask 'java'
cask 'keybase'
cask 'adoptopenjdk8'
cask 'launchbar'
cask 'paw'
cask 'postico'
cask 'qbserve'
cask 'quicken'
cask 'quickbooks-online' # TODO: or quickbooks
cask 'reggy'
cask 'sequel-pro'
cask 'signal'
cask 'sizeup'
cask 'slack'
cask 'superduper'
cask 'spotify'
cask 'textmate'
cask 'timely'
cask 'tower2'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'xscope'
cask 'zoomus'

# Fonts
cask 'font-glegoo'
cask 'font-inconsolata'
cask 'font-nexa-rust'
cask 'font-open-sans'
cask 'font-redacted'
cask 'font-roboto'
